"""Game-independent contracts for search and learning algorithms.

Adapters alone interpret states, action meaning, turn boundaries, hidden
information and evaluation. Native implementations provide an equivalent
compiled interface, with no Python dispatch in the search loop.
"""
from __future__ import annotations

from typing import Hashable, Protocol, Sequence, TypeVar

StateT = TypeVar("StateT")
ActionT = TypeVar("ActionT")


class SearchGame(Protocol[StateT, ActionT]):
    """Minimal shared interface for two-player decision search.

    State copying accepts reusable scratch storage. Action identifiers must be
    unique within an information set, and information-set identifiers must not
    expose opponent-hidden information.
    """

    def active_player(self, state: StateT) -> int: ...
    def is_terminal(self, state: StateT) -> bool: ...
    def frontier_ready(self, state: StateT) -> bool: ...
    def legal_actions(self, state: StateT) -> Sequence[ActionT]: ...
    def copy_state(self, source: StateT, reusable: StateT | None) -> StateT: ...
    def apply(self, state: StateT, action: ActionT) -> None: ...
    def completed_turn(
        self, before: StateT, after: StateT, action: ActionT
    ) -> bool: ...
    def state_key(self, state: StateT) -> Hashable: ...
    def information_set_id(self, state: StateT, player: int) -> Hashable: ...
    def action_id(self, action: ActionT) -> str: ...
    def is_priority_action(self, action: ActionT) -> bool: ...
    def action_score(self, state: StateT, player: int, action: ActionT) -> float: ...
    def evaluate(self, state: StateT, player: int) -> float: ...
    def terminal_utility(self, state: StateT, player: int) -> float: ...
