cdef class FastState:
    cdef int8_t deck[PLAYER_COUNT][MAX_DECK]
    cdef uint16_t deck_len[PLAYER_COUNT]
    cdef uint8_t deck_counts[PLAYER_COUNT][MAX_CARDS]
    cdef uint8_t hand[PLAYER_COUNT][MAX_CARDS]
    cdef uint8_t hand_len[PLAYER_COUNT]
    cdef int8_t discard[PLAYER_COUNT][MAX_DECK]
    cdef uint16_t discard_len[PLAYER_COUNT]

    cdef int8_t force[SLOT_COUNT]
    cdef int8_t bond[SLOT_COUNT]
    cdef int8_t name[SLOT_COUNT]
    cdef uint8_t exhausted[SLOT_COUNT]
    cdef int16_t temporary[SLOT_COUNT]
    cdef uint8_t negative_one_markers[SLOT_COUNT]
    cdef uint8_t negative_two_markers[SLOT_COUNT]
    cdef uint16_t suppression_mask[SLOT_COUNT]
    cdef uint8_t force_ability_used[SLOT_COUNT]
    cdef uint8_t bond_ability_used[SLOT_COUNT]
    cdef uint8_t name_ability_used[SLOT_COUNT]
    cdef uint8_t name_suppression_immune[SLOT_COUNT]
    cdef uint8_t maneuver_count[SLOT_COUNT]
    cdef uint8_t maneuvered_in_operation[SLOT_COUNT]

    cdef int8_t narrative[NARRATIVE_COUNT]
    cdef uint8_t narrative_front_mask[NARRATIVE_COUNT]
    cdef int8_t narrative_target_slot[NARRATIVE_COUNT]
    cdef uint8_t narrative_used[NARRATIVE_COUNT]
    cdef uint8_t narrative_direction[NARRATIVE_COUNT]
    cdef uint8_t narrative_trigger_mask[NARRATIVE_COUNT]
    cdef int8_t stratagem[PLAYER_COUNT]
    cdef uint8_t stratagem_revealed[PLAYER_COUNT]
    cdef uint8_t stratagem_known_to_mask[PLAYER_COUNT]
    cdef uint8_t stratagem_front_mask[PLAYER_COUNT]
    cdef uint8_t stratagem_direction[PLAYER_COUNT]
    cdef uint32_t stratagem_target_mask[PLAYER_COUNT]
    cdef uint8_t stratagem_used[PLAYER_COUNT]
    cdef uint8_t hero_used[PLAYER_COUNT]
    cdef uint16_t player_maneuver_count[PLAYER_COUNT]
    cdef int8_t maneuver_direction[SLOT_COUNT]

    cdef int8_t constraint_kind[MAX_CONSTRAINTS]
    cdef int8_t constraint_player[MAX_CONSTRAINTS]
    cdef int8_t constraint_source_card[MAX_CONSTRAINTS]
    cdef int8_t constraint_source_owner[MAX_CONSTRAINTS]
    cdef int8_t constraint_front[MAX_CONSTRAINTS]
    cdef int8_t constraint_direction[MAX_CONSTRAINTS]
    cdef int8_t constraint_source_slot[MAX_CONSTRAINTS]
    cdef int32_t constraint_activate_turn[MAX_CONSTRAINTS]
    cdef uint8_t constraint_flags[MAX_CONSTRAINTS]
    cdef uint8_t constraint_len

    cdef uint8_t known_hidden[PLAYER_COUNT][PLAYER_COUNT][MAX_CARDS]

    cdef uint8_t tax_owner[MAX_TAX_MARKERS]
    cdef uint8_t tax_target_player[MAX_TAX_MARKERS]
    cdef uint8_t tax_front[MAX_TAX_MARKERS]
    cdef uint8_t tax_amount[MAX_TAX_MARKERS]
    cdef uint8_t tax_card_type_mask[MAX_TAX_MARKERS]
    cdef int32_t tax_expires_turn[MAX_TAX_MARKERS]
    cdef uint8_t tax_len

    cdef uint8_t discount_owner[MAX_SLOT_DISCOUNTS]
    cdef uint8_t discount_target_player[MAX_SLOT_DISCOUNTS]
    cdef uint8_t discount_slot[MAX_SLOT_DISCOUNTS]
    cdef uint8_t discount_amount[MAX_SLOT_DISCOUNTS]
    cdef uint8_t discount_minimum[MAX_SLOT_DISCOUNTS]
    cdef uint8_t discount_card_type_mask[MAX_SLOT_DISCOUNTS]
    cdef int32_t discount_expires_turn[MAX_SLOT_DISCOUNTS]
    cdef uint8_t discount_len

    cdef uint8_t passed[PLAYER_COUNT]
    cdef int8_t pass_order[PLAYER_COUNT]
    cdef uint8_t pass_len
    cdef uint8_t discarded_this_battle[PLAYER_COUNT]
    cdef int16_t command[PLAYER_COUNT]
    cdef uint16_t operations_this_battle[PLAYER_COUNT]
    cdef uint8_t actions_this_turn
    cdef uint8_t closing_turns_remaining
    cdef uint8_t cards_played_this_turn_front_mask[PLAYER_COUNT]
    cdef uint8_t cards_played_this_battle_front_mask[PLAYER_COUNT]
    cdef uint8_t narratives_played_this_battle[PLAYER_COUNT]
    cdef int16_t command_spent_this_battle[PLAYER_COUNT]
    cdef int16_t command_refunded_this_battle[PLAYER_COUNT]
    cdef int16_t battle_start_command[PLAYER_COUNT]
    cdef int16_t battle_start_hand_size[PLAYER_COUNT]
    cdef int16_t cards_drawn_this_battle[PLAYER_COUNT]
    cdef int16_t completion_count_this_battle[PLAYER_COUNT]
    cdef int16_t deck_reshuffles[PLAYER_COUNT]
    cdef int16_t reshuffle_card_totals[PLAYER_COUNT]
    cdef int16_t reshuffle_hand_card_totals[PLAYER_COUNT]
    cdef uint8_t last_battle_valid
    cdef int16_t last_battle
    cdef int16_t last_front_scores[FRONT_COUNT][PLAYER_COUNT]
    cdef uint8_t last_lost_mask[PLAYER_COUNT]
    cdef int16_t last_command_start[PLAYER_COUNT]
    cdef int16_t last_command_spent[PLAYER_COUNT]
    cdef int16_t last_command_refunded[PLAYER_COUNT]
    cdef int16_t last_command_before_collapse[PLAYER_COUNT]
    cdef int16_t last_front_loss_command_penalty[PLAYER_COUNT]
    cdef int16_t last_recovery_actual[PLAYER_COUNT]
    cdef int16_t last_command_remaining[PLAYER_COUNT]
    cdef int16_t last_deck_remaining[PLAYER_COUNT]
    cdef int16_t last_hand_size[PLAYER_COUNT]
    cdef int16_t last_battle_start_hand_size[PLAYER_COUNT]
    cdef int16_t last_cards_drawn[PLAYER_COUNT]
    cdef int16_t last_completion_count[PLAYER_COUNT]
    cdef int16_t last_operations[PLAYER_COUNT]
    cdef int8_t last_pass_order[PLAYER_COUNT]
    cdef uint8_t last_pass_len
    cdef uint8_t cleanup_pending
    cdef uint8_t pending_draw_count
    cdef uint8_t pending_draw_finish_operation

    cdef int8_t pending_kind[MAX_PENDING_EFFECTS]
    cdef int8_t pending_player[MAX_PENDING_EFFECTS]
    cdef int8_t pending_card[MAX_PENDING_EFFECTS]
    cdef int8_t pending_command_source[MAX_PENDING_EFFECTS]
    cdef int8_t pending_source[MAX_PENDING_EFFECTS]
    cdef int8_t pending_aux[MAX_PENDING_EFFECTS]
    cdef uint32_t pending_source_mask[MAX_PENDING_EFFECTS]
    cdef uint32_t pending_dest_mask[MAX_PENDING_EFFECTS]
    cdef uint8_t pending_flags[MAX_PENDING_EFFECTS]
    cdef uint8_t pending_len
    cdef uint8_t pending_resume
    cdef int8_t pending_resume_player
    cdef uint8_t free_maneuver_available[PLAYER_COUNT]
    cdef int8_t free_maneuver_source[PLAYER_COUNT]

    cdef uint8_t resolution_stage
    cdef uint8_t resolution_lost_mask[PLAYER_COUNT]
    cdef uint8_t resolution_drive_mask[PLAYER_COUNT]
    cdef uint8_t resolution_protected_mask[PLAYER_COUNT]
    cdef int16_t resolution_front_loss_command_penalty[PLAYER_COUNT]
    cdef uint32_t resolution_suppressed_mask
    cdef int8_t resolution_contribution_front[SLOT_COUNT]
    cdef uint8_t resolution_cursor
    cdef int8_t resolution_starter

    cdef int8_t active_player
    cdef int16_t battle
    cdef int8_t phase
    cdef int8_t winner
    cdef int32_t turn_number
    cdef uint32_t shuffle_seed

    def __cinit__(self):
        memset(self.deck, 0xff, sizeof(self.deck))
        memset(self.deck_len, 0, sizeof(self.deck_len))
        memset(self.deck_counts, 0, sizeof(self.deck_counts))
        memset(self.hand, 0, sizeof(self.hand))
        memset(self.hand_len, 0, sizeof(self.hand_len))
        memset(self.discard, 0xff, sizeof(self.discard))
        memset(self.discard_len, 0, sizeof(self.discard_len))
        memset(self.force, 0xff, sizeof(self.force))
        memset(self.bond, 0xff, sizeof(self.bond))
        memset(self.name, 0xff, sizeof(self.name))
        memset(self.exhausted, 0, sizeof(self.exhausted))
        memset(self.temporary, 0, sizeof(self.temporary))
        memset(self.negative_one_markers, 0, sizeof(self.negative_one_markers))
        memset(self.negative_two_markers, 0, sizeof(self.negative_two_markers))
        memset(self.suppression_mask, 0, sizeof(self.suppression_mask))
        memset(self.force_ability_used, 0, sizeof(self.force_ability_used))
        memset(self.bond_ability_used, 0, sizeof(self.bond_ability_used))
        memset(self.name_ability_used, 0, sizeof(self.name_ability_used))
        memset(self.name_suppression_immune, 0, sizeof(self.name_suppression_immune))
        memset(self.maneuver_count, 0, sizeof(self.maneuver_count))
        memset(self.maneuvered_in_operation, 0, sizeof(self.maneuvered_in_operation))
        memset(self.narrative, 0xff, sizeof(self.narrative))
        memset(self.narrative_front_mask, 0, sizeof(self.narrative_front_mask))
        memset(self.narrative_target_slot, 0xff, sizeof(self.narrative_target_slot))
        memset(self.narrative_used, 0, sizeof(self.narrative_used))
        memset(self.narrative_direction, 0, sizeof(self.narrative_direction))
        memset(self.narrative_trigger_mask, 0, sizeof(self.narrative_trigger_mask))
        memset(self.stratagem, 0xff, sizeof(self.stratagem))
        memset(self.stratagem_revealed, 0, sizeof(self.stratagem_revealed))
        memset(self.stratagem_known_to_mask, 0, sizeof(self.stratagem_known_to_mask))
        memset(self.stratagem_front_mask, 0, sizeof(self.stratagem_front_mask))
        memset(self.stratagem_direction, 0, sizeof(self.stratagem_direction))
        memset(self.stratagem_target_mask, 0, sizeof(self.stratagem_target_mask))
        memset(self.stratagem_used, 0, sizeof(self.stratagem_used))
        memset(self.hero_used, 0, sizeof(self.hero_used))
        memset(self.player_maneuver_count, 0, sizeof(self.player_maneuver_count))
        memset(self.maneuver_direction, 0, sizeof(self.maneuver_direction))
        memset(self.constraint_kind, 0, sizeof(self.constraint_kind))
        memset(self.constraint_player, 0xff, sizeof(self.constraint_player))
        memset(self.constraint_source_card, 0xff, sizeof(self.constraint_source_card))
        memset(self.constraint_source_owner, 0xff, sizeof(self.constraint_source_owner))
        memset(self.constraint_front, 0xff, sizeof(self.constraint_front))
        memset(self.constraint_direction, 0, sizeof(self.constraint_direction))
        memset(self.constraint_source_slot, 0xff, sizeof(self.constraint_source_slot))
        memset(self.constraint_activate_turn, 0, sizeof(self.constraint_activate_turn))
        memset(self.constraint_flags, 0, sizeof(self.constraint_flags))
        self.constraint_len = 0
        memset(self.known_hidden, 0, sizeof(self.known_hidden))
        memset(self.tax_owner, 0, sizeof(self.tax_owner))
        memset(self.tax_target_player, 0, sizeof(self.tax_target_player))
        memset(self.tax_front, 0, sizeof(self.tax_front))
        memset(self.tax_amount, 0, sizeof(self.tax_amount))
        memset(self.tax_card_type_mask, 0, sizeof(self.tax_card_type_mask))
        memset(self.tax_expires_turn, 0xff, sizeof(self.tax_expires_turn))
        self.tax_len = 0
        memset(self.discount_owner, 0, sizeof(self.discount_owner))
        memset(self.discount_target_player, 0, sizeof(self.discount_target_player))
        memset(self.discount_slot, 0, sizeof(self.discount_slot))
        memset(self.discount_amount, 0, sizeof(self.discount_amount))
        memset(self.discount_minimum, 0, sizeof(self.discount_minimum))
        memset(self.discount_card_type_mask, 0, sizeof(self.discount_card_type_mask))
        memset(self.discount_expires_turn, 0xff, sizeof(self.discount_expires_turn))
        self.discount_len = 0
        memset(self.passed, 0, sizeof(self.passed))
        memset(self.pass_order, 0xff, sizeof(self.pass_order))
        memset(self.discarded_this_battle, 0, sizeof(self.discarded_this_battle))
        memset(self.command, 0, sizeof(self.command))
        memset(self.operations_this_battle, 0, sizeof(self.operations_this_battle))
        self.actions_this_turn = 0
        self.closing_turns_remaining = 0
        memset(self.cards_played_this_turn_front_mask, 0, sizeof(self.cards_played_this_turn_front_mask))
        memset(self.cards_played_this_battle_front_mask, 0, sizeof(self.cards_played_this_battle_front_mask))
        memset(self.narratives_played_this_battle, 0, sizeof(self.narratives_played_this_battle))
        memset(self.command_spent_this_battle, 0, sizeof(self.command_spent_this_battle))
        memset(self.command_refunded_this_battle, 0, sizeof(self.command_refunded_this_battle))
        memset(self.battle_start_command, 0, sizeof(self.battle_start_command))
        memset(self.battle_start_hand_size, 0, sizeof(self.battle_start_hand_size))
        memset(self.cards_drawn_this_battle, 0, sizeof(self.cards_drawn_this_battle))
        memset(self.completion_count_this_battle, 0, sizeof(self.completion_count_this_battle))
        memset(self.deck_reshuffles, 0, sizeof(self.deck_reshuffles))
        memset(self.reshuffle_card_totals, 0, sizeof(self.reshuffle_card_totals))
        memset(self.reshuffle_hand_card_totals, 0, sizeof(self.reshuffle_hand_card_totals))
        self.last_battle_valid = 0
        self.last_battle = 0
        memset(self.last_front_scores, 0, sizeof(self.last_front_scores))
        memset(self.last_lost_mask, 0, sizeof(self.last_lost_mask))
        memset(self.last_command_start, 0, sizeof(self.last_command_start))
        memset(self.last_command_spent, 0, sizeof(self.last_command_spent))
        memset(self.last_command_refunded, 0, sizeof(self.last_command_refunded))
        memset(self.last_command_before_collapse, 0, sizeof(self.last_command_before_collapse))
        memset(self.last_front_loss_command_penalty, 0, sizeof(self.last_front_loss_command_penalty))
        memset(self.last_recovery_actual, 0, sizeof(self.last_recovery_actual))
        memset(self.last_command_remaining, 0, sizeof(self.last_command_remaining))
        memset(self.last_deck_remaining, 0, sizeof(self.last_deck_remaining))
        memset(self.last_hand_size, 0, sizeof(self.last_hand_size))
        memset(self.last_battle_start_hand_size, 0, sizeof(self.last_battle_start_hand_size))
        memset(self.last_cards_drawn, 0, sizeof(self.last_cards_drawn))
        memset(self.last_completion_count, 0, sizeof(self.last_completion_count))
        memset(self.last_operations, 0, sizeof(self.last_operations))
        memset(self.last_pass_order, 0xff, sizeof(self.last_pass_order))
        self.last_pass_len = 0
        self.cleanup_pending = 0
        self.pending_draw_count = 0
        self.pending_draw_finish_operation = 0
        memset(self.pending_kind, 0, sizeof(self.pending_kind))
        memset(self.pending_player, 0xff, sizeof(self.pending_player))
        memset(self.pending_card, 0xff, sizeof(self.pending_card))
        memset(self.pending_command_source, 0xff, sizeof(self.pending_command_source))
        memset(self.pending_source, 0xff, sizeof(self.pending_source))
        memset(self.pending_aux, 0xff, sizeof(self.pending_aux))
        memset(self.pending_source_mask, 0, sizeof(self.pending_source_mask))
        memset(self.pending_dest_mask, 0, sizeof(self.pending_dest_mask))
        memset(self.pending_flags, 0, sizeof(self.pending_flags))
        self.pending_len = 0
        self.pending_resume = RESUME_NONE
        self.pending_resume_player = -1
        memset(self.free_maneuver_available, 0, sizeof(self.free_maneuver_available))
        memset(self.free_maneuver_source, 0xff, sizeof(self.free_maneuver_source))
        self.resolution_stage = RESOLUTION_NONE
        memset(self.resolution_lost_mask, 0, sizeof(self.resolution_lost_mask))
        memset(self.resolution_drive_mask, 0, sizeof(self.resolution_drive_mask))
        memset(self.resolution_protected_mask, 0, sizeof(self.resolution_protected_mask))
        memset(self.resolution_front_loss_command_penalty, 0, sizeof(self.resolution_front_loss_command_penalty))
        self.resolution_suppressed_mask = 0
        memset(self.resolution_contribution_front, 0xff, sizeof(self.resolution_contribution_front))
        self.resolution_cursor = 0
        self.resolution_starter = -1
        self.pass_len = 0
        self.active_player = 0
        self.battle = 1
        self.phase = PHASE_BATTLE
        self.winner = -1
        self.turn_number = 0
        self.shuffle_seed = 0

    cdef void copy_from_fast(self, FastState other) noexcept:
        memcpy(self.deck, other.deck, sizeof(self.deck))
        memcpy(self.deck_len, other.deck_len, sizeof(self.deck_len))
        memcpy(self.deck_counts, other.deck_counts, sizeof(self.deck_counts))
        memcpy(self.hand, other.hand, sizeof(self.hand))
        memcpy(self.hand_len, other.hand_len, sizeof(self.hand_len))
        memcpy(self.discard, other.discard, sizeof(self.discard))
        memcpy(self.discard_len, other.discard_len, sizeof(self.discard_len))
        memcpy(self.force, other.force, sizeof(self.force))
        memcpy(self.bond, other.bond, sizeof(self.bond))
        memcpy(self.name, other.name, sizeof(self.name))
        memcpy(self.exhausted, other.exhausted, sizeof(self.exhausted))
        memcpy(self.temporary, other.temporary, sizeof(self.temporary))
        memcpy(self.negative_one_markers, other.negative_one_markers, sizeof(self.negative_one_markers))
        memcpy(self.negative_two_markers, other.negative_two_markers, sizeof(self.negative_two_markers))
        memcpy(self.suppression_mask, other.suppression_mask, sizeof(self.suppression_mask))
        memcpy(self.force_ability_used, other.force_ability_used, sizeof(self.force_ability_used))
        memcpy(self.bond_ability_used, other.bond_ability_used, sizeof(self.bond_ability_used))
        memcpy(self.name_ability_used, other.name_ability_used, sizeof(self.name_ability_used))
        memcpy(self.name_suppression_immune, other.name_suppression_immune, sizeof(self.name_suppression_immune))
        memcpy(self.maneuver_count, other.maneuver_count, sizeof(self.maneuver_count))
        memcpy(self.maneuvered_in_operation, other.maneuvered_in_operation, sizeof(self.maneuvered_in_operation))
        memcpy(self.narrative, other.narrative, sizeof(self.narrative))
        memcpy(self.narrative_front_mask, other.narrative_front_mask, sizeof(self.narrative_front_mask))
        memcpy(self.narrative_target_slot, other.narrative_target_slot, sizeof(self.narrative_target_slot))
        memcpy(self.narrative_used, other.narrative_used, sizeof(self.narrative_used))
        memcpy(self.narrative_direction, other.narrative_direction, sizeof(self.narrative_direction))
        memcpy(self.narrative_trigger_mask, other.narrative_trigger_mask, sizeof(self.narrative_trigger_mask))
        memcpy(self.stratagem, other.stratagem, sizeof(self.stratagem))
        memcpy(self.stratagem_revealed, other.stratagem_revealed, sizeof(self.stratagem_revealed))
        memcpy(self.stratagem_known_to_mask, other.stratagem_known_to_mask, sizeof(self.stratagem_known_to_mask))
        memcpy(self.stratagem_front_mask, other.stratagem_front_mask, sizeof(self.stratagem_front_mask))
        memcpy(self.stratagem_direction, other.stratagem_direction, sizeof(self.stratagem_direction))
        memcpy(self.stratagem_target_mask, other.stratagem_target_mask, sizeof(self.stratagem_target_mask))
        memcpy(self.stratagem_used, other.stratagem_used, sizeof(self.stratagem_used))
        memcpy(self.hero_used, other.hero_used, sizeof(self.hero_used))
        memcpy(self.player_maneuver_count, other.player_maneuver_count, sizeof(self.player_maneuver_count))
        memcpy(self.maneuver_direction, other.maneuver_direction, sizeof(self.maneuver_direction))
        memcpy(self.constraint_kind, other.constraint_kind, sizeof(self.constraint_kind))
        memcpy(self.constraint_player, other.constraint_player, sizeof(self.constraint_player))
        memcpy(self.constraint_source_card, other.constraint_source_card, sizeof(self.constraint_source_card))
        memcpy(self.constraint_source_owner, other.constraint_source_owner, sizeof(self.constraint_source_owner))
        memcpy(self.constraint_front, other.constraint_front, sizeof(self.constraint_front))
        memcpy(self.constraint_direction, other.constraint_direction, sizeof(self.constraint_direction))
        memcpy(self.constraint_source_slot, other.constraint_source_slot, sizeof(self.constraint_source_slot))
        memcpy(self.constraint_activate_turn, other.constraint_activate_turn, sizeof(self.constraint_activate_turn))
        memcpy(self.constraint_flags, other.constraint_flags, sizeof(self.constraint_flags))
        self.constraint_len = other.constraint_len
        memcpy(self.known_hidden, other.known_hidden, sizeof(self.known_hidden))
        memcpy(self.tax_owner, other.tax_owner, sizeof(self.tax_owner))
        memcpy(self.tax_target_player, other.tax_target_player, sizeof(self.tax_target_player))
        memcpy(self.tax_front, other.tax_front, sizeof(self.tax_front))
        memcpy(self.tax_amount, other.tax_amount, sizeof(self.tax_amount))
        memcpy(self.tax_card_type_mask, other.tax_card_type_mask, sizeof(self.tax_card_type_mask))
        memcpy(self.tax_expires_turn, other.tax_expires_turn, sizeof(self.tax_expires_turn))
        self.tax_len = other.tax_len
        memcpy(self.discount_owner, other.discount_owner, sizeof(self.discount_owner))
        memcpy(self.discount_target_player, other.discount_target_player, sizeof(self.discount_target_player))
        memcpy(self.discount_slot, other.discount_slot, sizeof(self.discount_slot))
        memcpy(self.discount_amount, other.discount_amount, sizeof(self.discount_amount))
        memcpy(self.discount_minimum, other.discount_minimum, sizeof(self.discount_minimum))
        memcpy(self.discount_card_type_mask, other.discount_card_type_mask, sizeof(self.discount_card_type_mask))
        memcpy(self.discount_expires_turn, other.discount_expires_turn, sizeof(self.discount_expires_turn))
        self.discount_len = other.discount_len
        memcpy(self.passed, other.passed, sizeof(self.passed))
        memcpy(self.pass_order, other.pass_order, sizeof(self.pass_order))
        memcpy(self.discarded_this_battle, other.discarded_this_battle, sizeof(self.discarded_this_battle))
        memcpy(self.command, other.command, sizeof(self.command))
        memcpy(self.operations_this_battle, other.operations_this_battle, sizeof(self.operations_this_battle))
        self.actions_this_turn = other.actions_this_turn
        self.closing_turns_remaining = other.closing_turns_remaining
        memcpy(self.cards_played_this_turn_front_mask, other.cards_played_this_turn_front_mask, sizeof(self.cards_played_this_turn_front_mask))
        memcpy(self.cards_played_this_battle_front_mask, other.cards_played_this_battle_front_mask, sizeof(self.cards_played_this_battle_front_mask))
        memcpy(self.narratives_played_this_battle, other.narratives_played_this_battle, sizeof(self.narratives_played_this_battle))
        memcpy(self.command_spent_this_battle, other.command_spent_this_battle, sizeof(self.command_spent_this_battle))
        memcpy(self.command_refunded_this_battle, other.command_refunded_this_battle, sizeof(self.command_refunded_this_battle))
        memcpy(self.battle_start_command, other.battle_start_command, sizeof(self.battle_start_command))
        memcpy(self.battle_start_hand_size, other.battle_start_hand_size, sizeof(self.battle_start_hand_size))
        memcpy(self.cards_drawn_this_battle, other.cards_drawn_this_battle, sizeof(self.cards_drawn_this_battle))
        memcpy(self.completion_count_this_battle, other.completion_count_this_battle, sizeof(self.completion_count_this_battle))
        memcpy(self.deck_reshuffles, other.deck_reshuffles, sizeof(self.deck_reshuffles))
        memcpy(self.reshuffle_card_totals, other.reshuffle_card_totals, sizeof(self.reshuffle_card_totals))
        memcpy(self.reshuffle_hand_card_totals, other.reshuffle_hand_card_totals, sizeof(self.reshuffle_hand_card_totals))
        self.last_battle_valid = other.last_battle_valid
        self.last_battle = other.last_battle
        memcpy(self.last_front_scores, other.last_front_scores, sizeof(self.last_front_scores))
        memcpy(self.last_lost_mask, other.last_lost_mask, sizeof(self.last_lost_mask))
        memcpy(self.last_command_start, other.last_command_start, sizeof(self.last_command_start))
        memcpy(self.last_command_spent, other.last_command_spent, sizeof(self.last_command_spent))
        memcpy(self.last_command_refunded, other.last_command_refunded, sizeof(self.last_command_refunded))
        memcpy(self.last_command_before_collapse, other.last_command_before_collapse, sizeof(self.last_command_before_collapse))
        memcpy(self.last_front_loss_command_penalty, other.last_front_loss_command_penalty, sizeof(self.last_front_loss_command_penalty))
        memcpy(self.last_recovery_actual, other.last_recovery_actual, sizeof(self.last_recovery_actual))
        memcpy(self.last_command_remaining, other.last_command_remaining, sizeof(self.last_command_remaining))
        memcpy(self.last_deck_remaining, other.last_deck_remaining, sizeof(self.last_deck_remaining))
        memcpy(self.last_hand_size, other.last_hand_size, sizeof(self.last_hand_size))
        memcpy(self.last_battle_start_hand_size, other.last_battle_start_hand_size, sizeof(self.last_battle_start_hand_size))
        memcpy(self.last_cards_drawn, other.last_cards_drawn, sizeof(self.last_cards_drawn))
        memcpy(self.last_completion_count, other.last_completion_count, sizeof(self.last_completion_count))
        memcpy(self.last_operations, other.last_operations, sizeof(self.last_operations))
        memcpy(self.last_pass_order, other.last_pass_order, sizeof(self.last_pass_order))
        self.last_pass_len = other.last_pass_len
        self.cleanup_pending = other.cleanup_pending
        self.pending_draw_count = other.pending_draw_count
        self.pending_draw_finish_operation = other.pending_draw_finish_operation
        memcpy(self.pending_kind, other.pending_kind, sizeof(self.pending_kind))
        memcpy(self.pending_player, other.pending_player, sizeof(self.pending_player))
        memcpy(self.pending_card, other.pending_card, sizeof(self.pending_card))
        memcpy(self.pending_command_source, other.pending_command_source, sizeof(self.pending_command_source))
        memcpy(self.pending_source, other.pending_source, sizeof(self.pending_source))
        memcpy(self.pending_aux, other.pending_aux, sizeof(self.pending_aux))
        memcpy(self.pending_source_mask, other.pending_source_mask, sizeof(self.pending_source_mask))
        memcpy(self.pending_dest_mask, other.pending_dest_mask, sizeof(self.pending_dest_mask))
        memcpy(self.pending_flags, other.pending_flags, sizeof(self.pending_flags))
        self.pending_len = other.pending_len
        self.pending_resume = other.pending_resume
        self.pending_resume_player = other.pending_resume_player
        memcpy(self.free_maneuver_available, other.free_maneuver_available, sizeof(self.free_maneuver_available))
        memcpy(self.free_maneuver_source, other.free_maneuver_source, sizeof(self.free_maneuver_source))
        self.resolution_stage = other.resolution_stage
        memcpy(self.resolution_lost_mask, other.resolution_lost_mask, sizeof(self.resolution_lost_mask))
        memcpy(self.resolution_drive_mask, other.resolution_drive_mask, sizeof(self.resolution_drive_mask))
        memcpy(self.resolution_protected_mask, other.resolution_protected_mask, sizeof(self.resolution_protected_mask))
        memcpy(self.resolution_front_loss_command_penalty, other.resolution_front_loss_command_penalty, sizeof(self.resolution_front_loss_command_penalty))
        self.resolution_suppressed_mask = other.resolution_suppressed_mask
        memcpy(self.resolution_contribution_front, other.resolution_contribution_front, sizeof(self.resolution_contribution_front))
        self.resolution_cursor = other.resolution_cursor
        self.resolution_starter = other.resolution_starter
        self.pass_len = other.pass_len
        self.active_player = other.active_player
        self.battle = other.battle
        self.phase = other.phase
        self.winner = other.winner
        self.turn_number = other.turn_number
        self.shuffle_seed = other.shuffle_seed

    cdef FastState clone_fast(self):
        cdef FastState other = FastState()
        other.copy_from_fast(self)
        return other

    cpdef FastState clone(self):
        return self.clone_fast()

    cpdef copy_from(self, FastState other):
        self.copy_from_fast(other)
