from __future__ import annotations

import argparse
from pathlib import Path

from longwar.game.model import Front, RANK_INDEX, Rank
from longwar.protocol import (
    Direction,
    DirectionCode,
    NARRATIVE_STORAGE_CAPACITY_PER_PLAYER,
    PLAYER_COUNT,
)

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "src" / "longwar" / "_fast_protocol.generated.pxi"


def render() -> str:
    values = (
        ("PLAYER_COUNT", PLAYER_COUNT),
        ("FRONT_COUNT", len(Front)),
        ("RANK_COUNT", len(Rank)),
        ("DIRECTION_COUNT", len(Direction)),
        (
            "NARRATIVE_SLOTS_PER_PLAYER",
            NARRATIVE_STORAGE_CAPACITY_PER_PLAYER,
        ),
        ("RANK_FRONT", RANK_INDEX[Rank.FRONT]),
        ("RANK_REAR", RANK_INDEX[Rank.REAR]),
        ("DIRECTION_NONE", int(DirectionCode.NONE)),
        ("DIRECTION_LEFT", int(DirectionCode.LEFT)),
        ("DIRECTION_RIGHT", int(DirectionCode.RIGHT)),
    )
    lines = [
        "# Generated by tools/build_native_protocol.py. Do not edit by hand.",
        *(f"DEF {name} = {value}" for name, value in values),
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        actual = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if actual != expected:
            raise SystemExit(
                "src/longwar/_fast_protocol.generated.pxi is stale; run "
                "python tools/build_native_protocol.py"
            )
        print("Native protocol is current")
        return
    OUTPUT.write_text(expected, encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
