from __future__ import annotations

import argparse
import json
from pathlib import Path
from enum import Enum

from longwar.game.model import Phase, Rank
from longwar.protocol import (
    ActionKind,
    CardType,
    Direction,
    ForceRole,
    GameMode,
    NarrativeForm,
    PlaySetupMode,
    PolicySource,
    RuleBlockField,
    RuleBlockKind,
)

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "web" / "protocol.generated.js"


def enum_payload(enum_type: type[Enum]) -> dict[str, object]:
    return {item.name: item.value for item in enum_type}


def payload() -> dict[str, dict[str, object]]:
    return {
        "actionKind": enum_payload(ActionKind),
        "cardType": enum_payload(CardType),
        "direction": enum_payload(Direction),
        "forceRole": enum_payload(ForceRole),
        "gameMode": enum_payload(GameMode),
        "narrativeForm": enum_payload(NarrativeForm),
        "phase": enum_payload(Phase),
        "playSetupMode": enum_payload(PlaySetupMode),
        "policySource": enum_payload(PolicySource),
        "rank": enum_payload(Rank),
        "ruleBlockField": enum_payload(RuleBlockField),
        "ruleBlockKind": enum_payload(RuleBlockKind),
    }


def render() -> str:
    encoded = json.dumps(payload(), indent=2, sort_keys=True)
    return (
        "/* Generated by tools/build_web_protocol.py. Do not edit by hand. */\n"
        f"const LW_PROTOCOL_DATA = {encoded};\n"
        "for (const value of Object.values(LW_PROTOCOL_DATA)) Object.freeze(value);\n"
        "globalThis.LW_PROTOCOL = Object.freeze(LW_PROTOCOL_DATA);\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        actual = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if actual != expected:
            raise SystemExit(
                "web/protocol.generated.js is stale; run "
                "python tools/build_web_protocol.py"
            )
        print("Browser protocol is current")
        return
    OUTPUT.write_text(expected, encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
