from __future__ import annotations

import argparse
from pathlib import Path

from longwar.native_fingerprint import current_native_source_fingerprint

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "src" / "longwar" / "_native_source_fingerprint.generated.pxi"


def render() -> str:
    fingerprint = current_native_source_fingerprint()
    return (
        "# Generated by tools/build_native_fingerprint.py. Do not edit by hand.\n"
        "NATIVE_SOURCE_CHECKABLE = True\n"
        f'NATIVE_SOURCE_FINGERPRINT = "{fingerprint}"\n'
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        actual = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if actual != expected:
            raise SystemExit(
                "src/longwar/_native_source_fingerprint.generated.pxi is stale; "
                "run python tools/build_native_fingerprint.py"
            )
        print("Native source fingerprint is current")
        return
    OUTPUT.write_text(expected, encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
