from __future__ import annotations

import argparse
from pathlib import Path
from longwar.heuristics import HEURISTIC_DEFAULTS, HEURISTIC_KEYS

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "src" / "longwar" / "_heuristic_weights.generated.pxi"

def _cython_name(key: str) -> str:
    return "HW_" + key.upper()

def render() -> str:
    lines = [
        "# Generated by tools/build_heuristic_weights.py. Do not edit by hand.",
        f"DEF HEUR_WEIGHT_COUNT = {len(HEURISTIC_KEYS)}",
        *(f"DEF {_cython_name(key)} = {index}" for index, key in enumerate(HEURISTIC_KEYS)),
        "",
        "cdef inline void _heuristic_load_defaults(double* values) noexcept:",
        *(f"    values[{_cython_name(key)}] = {HEURISTIC_DEFAULTS[key]!r}" for key in HEURISTIC_KEYS),
        "",
    ]
    return "\n".join(lines)

def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        actual = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if actual != expected:
            raise SystemExit(
                "src/longwar/_heuristic_weights.generated.pxi is stale; run "
                "python tools/build_heuristic_weights.py"
            )
        print("Heuristic weight protocol is current")
        return
    OUTPUT.write_text(expected, encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(ROOT)}")

if __name__ == "__main__":
    main()
